### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by shulan-moe** [Bluefissure/FFXIVBOT#21]
CANNOT build normally after commits today.
I build it successfully yesterday.

```
(venv-ffxivbot) root@VM-0-2-ubuntu:/home/FFXIVBOT# python3 manage.py check
initializing` pika publisher
System check identified some issues:

WARNINGS:
ffxivbot.HuntGroup.moderator: (fields.W340) null has no effect on ManyToManyField.

System check identified 1 issue (0 silenced).`
```

```
(venv-ffxivbot) root@VM-0-2-ubuntu:/home/FFXIVBOT/ffxivbot# python3 pika_rabbit.py
INFO:__main__:Connecting to amqp://guest:guest@localhost:5672/?heartbeat=600
Traceback (most recent call last):
  File "pika_rabbit.py", line 836, in <module>
    main()
  File "pika_rabbit.py", line 830, in main
    pikapika.run()
  File "pika_rabbit.py", line 799, in run
    self._connection = self.connect()
  File "pika_rabbit.py", line 183, in connect
    parameters, self.on_connection_open, stop_ioloop_on_close=False
TypeError: __init__() got an unexpected keyword argument 'stop_ioloop_on_close'
```
Please add a dev branch and merge to master when make sure it stable.

**Comment by Bluefissure** [comment]
Yeah, this problem is caused by a broken CI at [Job#206](https://travis-ci.org/Bluefissure/FFXIVBOT/builds/562984629), I updated the pika version to check whether it can be fixed but unfortunately, no.
I think [travis CI](https://travis-ci.org/) is broken at the `rabbitmq` service, a newer version of `pika` can't fix that and may lead to new problems like what you encountered just now, so I roll back the master branch after that.
Yes, I'll add a dev branch to add new features and merge stable ones to master. Thanks.
